### ISSUE TITLE
Parsing invalid files?

### ISSUE THREAD

**Issue by jnicklas** [Oktavilla/total-in-ruby#3]
We should define somehow what happens when the parser is fed with a file which is not a valid TotalIN file. How do even determine if a file is a valid TotalIN file?

One sensible heuristic would be to look for the following two markers:
- Line 1, column 0-1 should be "00"
- Line 1, column 37-39 should be "TL1"

If these conditions are not met, we'll simply bail and abort parsing with an error. Sounds reasonable?

**Comment by joeljunstrom** [comment]
:+1: The only other assertion I can think of would be that it has a width of exactly 80 characters.
